name: Run Python Script

on:
  workflow_dispatch:  # Manually triggered workflow
    inputs:
      run_script:
        description: 'Run the script'
        required: true
        default: 'yes'
      duration:
        description: 'Duration in minutes to run the script'
        required: true
        default: '120'  # Default to 2 hours (120 minutes)

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      USER_EMAIL: ${{ secrets.USER_EMAIL }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      TWILIO_FROM_PHONE: ${{ secrets.TWILIO_FROM_PHONE }}
      TWILIO_TO_PHONE: ${{ secrets.TWILIO_TO_PHONE }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token to trigger the workflow

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: |
          duration_minutes=${{ github.event.inputs.duration }}
          end_time=$(( $(date +%s) + duration_minutes * 60 ))
          echo "Running login.py for $duration_minutes minutes..."
          
          while [ $(date +%s) -lt $end_time ]; do
            echo "⏱️ Running login.py"
            python login.py 
            exit_code=$?
            if [ $exit_code -eq 99 ]; then
              echo "Stream is down, exiting..."
              exit 0
            elif [ $exit_code -ne 0 ]; then
              echo "unexpected error occurred, exiting with failure..."
              exit 1
            fi
            sleep 60  # Wait for 1 minute before running again
          done

      - name: Trigger workflow recursively
        if: success()
        run: |
          if [[ "${{ github.event.inputs.run_script }}" == "yes" ]]; then
            echo "Triggering the workflow recursively..."
            curl -X POST \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Content-Type: application/json" \
              -d '{"ref": "main"}' \
              https://api.github.com/repos/${{ github.repository }}/actions/workflows/run-python-script.yml/dispatches
          fi