name: On-Demand Repeating Python Script

on:
  workflow_dispatch:
    inputs:
      minutes:
        description: "How many minutes should the script run?"
        required: true
        default: "120"  # default is 2 hours

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      TWILIO_FROM_PHONE: ${{ secrets.TWILIO_FROM_PHONE }}
      TWILIO_TO_PHONE: ${{ secrets.TWILIO_TO_PHONE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
        python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run login.py every minute
        shell: bash
        run: |
          echo "Running for ${{ github.event.inputs.minutes }} minutes..."
          for ((i=1; i<=${{ github.event.inputs.minutes }}; i++)); do
            echo "⏱️ Minute $i: Running login.py"
            python login.py
            sleep 60
          done